{
 "title": "3. Handling Multiple Data Sources",
 "description": "This dashboard illustrates the problems that arise when trying to display metrics from multiple cloud data sources.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "Data source", "query": "graphite" },
   { "name": "ds_multi", "label": "Data source (multi-value)", "query": "graphite" }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Introduction\n\nThis dashboard explores our current understanding of how to handle multiple\ncloud data sources within a single dashboard. Each panel has a description\nthat you can read by hovering over the (i) icon next to the panel title.\nYou can also view the actual configuration of the panel by clicking on the\nthree dots and \"Edit.\" You can make any changes you wish without affecting\nother users. Those changes are only saved when you click \"Save\" in the top\nright."
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "## Variables\n\nVariables can be defined for each dashboard and then referenced in panel\nconfiguration and metric queries. These variables can be set by selecting\nvalues in the dropdown menus above.\n\nThese variables are created and configured in the dashboard settings. Click\nthe cog in the top right and go to the \"Variables\" tab. These variables can\nbe used for the data source of metric queries. You can also include variables\nin panel text or configuration by referencing it as `${var_name:optional format}`.\nFor more information, see https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax."
   }
  },
  { "title": "Metric Examples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "API Errors (single cloud, \"ds\" variable data source)",
   "type": "timeseries",
   "description": "This panel uses the single-valued data source variable, then queries the `api.meter.http.failure.one-minute` metric. Try changing the \"Data source\" dropdown at the top and see how the panel updates.\n\nCurrent data source: ${ds:text}",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "api.meter.http.failure.one-minute"
    }
   ]
  },
  {
   "title": "API Successes and Errors (single cloud, metric wildcard)",
   "type": "timeseries",
   "description": "Elements of a graphite metric can be \"wildcarded,\" which causes the panel to display multiple time series. It would be great if we could replicate this behavior for multiple data sources. However, the data source does not appear in the metric name and cannot be wildcarded.\n\nMaybe you could build a plugin that presents an \"aggregate\" data source that includes the name of each underlying data source as an element in the metric name. That way, we could build panels with wildcards for the data source. However, be aware that the metric query format you see here is specific to Graphite and may differ for other metric databases like Prometheus.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "target": "api.meter.http.*.one-minute" }
   ]
  },
  {
   "title": "API Errors (\"ds_multi\" variable data source)",
   "type": "timeseries",
   "description": "The multi-valued variable \"ds-multi\" _can_ be used as a panel's data source. However, the panel does not work as expected if you set the variable to multiple values in the dropdown. The intended way to use a multi-valued data source variable is to configure the panel to repeat itself for each value, as demonstrated in the next row.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "api.meter.http.failure.one-minute"
    }
   ]
  },
  {
   "title": "API Errors (multiple clouds, mixed data source)",
   "type": "timeseries",
   "description": "This panel uses the special \"Mixed\" data source, which allows you to specify a different data source for each metric query. Unfortunately, this requires you to repeat your query for every data source you want to display. This is painful and brittle, since if we later add a new cloud, we'd have to update all existing panels that use this \"Mixed\" approach.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "alias(api.meter.http.failure.one-minute, 'Atwood HTTP Failures')"
    },
    {
     "target": "alias(api.meter.http.failure.one-minute, 'Linde HTTP Failures')"
    },
    {
     "target": "alias(api.meter.http.failure.one-minute, 'Sontag HTTP Failures')"
    }
   ]
  },
  { "title": "Repeating a Panel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "API Failures - ${ds_multi:text} (multiple clouds, repeating panel)",
   "type": "timeseries",
   "description": "This panel is configured to repeat itself for every selected value in variable `ds_multi`. Unfortunately, this means that the information is spread across multiple panels. What's more, setting up a panel to repeat is a pain, because your changes do not automatically take effect until you save the dashboard and reload the page.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "repeat": "ds_multi",
   "targets": [
    {
     "target": "api.meter.http.failure.one-minute"
    }
   ]
  },
  {
   "title": "Repeating a Row - ${ds_multi:text}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "ds_multi"
  },
  {
   "title": "API Failures - ${ds_multi:text} (multiple clouds, repeating row)",
   "type": "timeseries",
   "description": "Rows can be configured to repeat themselves for each value of a variable, just like panels. There is a cog next to the row name that appears when you hover over the row. Here, you do not configure the panels to repeat, but you still reference the multi-valued variable as the data source. This allows you to repeat multiple panels, but we still have the problem of spreading cloud information across multiple locations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "target": "api.meter.http.failure.one-minute"
    }
   ]
  },
  {
   "title": "API Successes - ${ds_multi:text} (multiple clouds, repeating row)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "target": "api.meter.http.success.one-minute"
    }
   ]
  }
 ]
}