{
 "title": "2. Service Dashboards and Unused Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Service Dashboards\n\nOur general convention at CrowdStrike is to have a Grafana dashboard for each\nmicroservice. The Site Reliability Engineering team (SRE, my team) relies on\nthese dashboards to get a quick understanding of the health of a service. If we\nsee that the service is having problems, it's helpful to look for anomalies in\nthe graphs, like elevated latency from a database, an unexpected drop in\nincoming traffic, or a high error rate on specific types of requests."
   }
  },
  {
   "title": "API Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "api.meter.http.success.one-minute"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "options": {
    "content": "# Unused Metrics\n\nUnfortunately, we currently have millions of those metrics. Not all of those\nmetrics appear on dashboards for us to view. An unused metric could be something\nunhelpful that can be removed from the service's source code, or it could be\nsomething important that we want to include on the dashboard. However, we\ncurrently have no idea which service metrics are unused.\n\nYour first task this year will be to develop a tool to identify service metrics\nthat are not present in a dashboard. You will likely need to use the Graphite\nAPI to find metric names stored in Graphite, then compare that to the metric\nqueries within a Grafana dashboard's JSON model.\n\nFor example, in this dashboard, `api.meter.http.success.*`,\n`api.meter.http.failure.*`, and `api.timer.response.*` are used, while\n`api.meter.useless-metric.*` are unused.\n\nI'm using a wildcard at the end of those metric names to denote that if any of\nthe generated suffixes like `count` or `one-minute` appear in the dashboard,\nthen all of them should be considered used."
   }
  },
  {
   "title": "API Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "api.meter.http.failure.one-minute"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": {
    "content": "# Creating Dashboards\n\nCurrently, service dashboards are created manually be the service owners. As\ndescribed above, this can lead to unused metrics. It's also a time-intensive\nprocess that nobody really likes doing. Your second task is to create a tool\nto help teams automatically generate starter dashboards for their services. It\nwould be nice if this tool could be interactive and helps guide the team through\nthe dashboard creation process. The generated dashboards should be ready for\nfuture modifications with or without the generation tool.\n\nTo get you started, try creating a dashboard manually for the mock \"frontend\"\nservice. This will show you the process of identifying which metrics are present\nin Graphite and what visualizations are possible."
   }
  },
  {
   "title": "Average API Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "target": "api.timer.response.mean" }
   ]
  }
 ]
}